name: myschedule
description: A grate TO DO TASK Flutter project using Firebase.
publish_to: 'googlePlay'
version: 1.2.2+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.1
  crypto: ^3.0.3
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_gallery_saver: ^2.0.2
  image_picker: ^0.8.9
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  timezone: ^0.9.2
  awesome_notifications: ^0.6.19
  google_sign_in: ^6.1.4
  image_cropper: ^4.0.1
  file_picker: ^5.3.2
  file_selector: ^0.9.4
  flutter_secure_storage: ^8.0.0
  flutter_facebook_auth: ^5.0.11
  firebase_messaging: ^14.6.4
  intl: ^0.18.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  package_info: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/facebook_logo.png
    - assets/images/google_logo.png
    - assets/ic_launcher.png


